config/routes.rb
Dbros::Application.routes.draw do

 
  devise_for :admins

  resources :name_societies

  resources :societies

  resources :investigations

  resources :galleries

  resources :fascicles

  resources :dossiers

  resources :unions

  resources :associations

  resources :ambits

 	
  devise_for :users
  resources :users

 	
  resources :areas
 	resources :names
 	

	
	match '/names_search' => 'names#names_search'
	match '/show_search_results' => 'names#show_search_results'
	
	

	
	
	
	
	

  get "home/index"
  root :to => "home#index" 

end

app/models/dossier.rb
class Dossier < ActiveRecord::Base
  has_and_belongs_to_many :names

  has_and_belongs_to_many :associations
  has_and_belongs_to_many :unions
  has_and_belongs_to_many :societies


	validates_attachment_presence :documento, :message => ":  campo vuoto!"
	
  has_attached_file :documento, 
    :url  => "/assets/dossiers/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/dossiers/:id/:style/:basename.:extension"
    
    


end

app/controllers/dossiers_controller.rb
class DossiersController < ApplicationController
  # GET /dossiers
  # GET /dossiers.xml
  before_filter :authenticate_user!, :except => [:show, :index]
  
  helper_method :sort_column, :sort_direction
  
  def index
    @dossiers = Dossier.order(sort_column + ' ' + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dossiers }
    end
  end

  # GET /dossiers/1
  # GET /dossiers/1.xml
  def show
    @dossier = Dossier.find(params[:id])
    @names = @dossier.names
   	@unions = @dossier.unions 
    @societies = @dossier.societies

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dossier }
    end
  end

  # GET /dossiers/new
  # GET /dossiers/new.xml
  def new
     @dossier = Dossier.new
     @names = Name.order("cognome_nome ASC")
     @unions = Union.order("denominazione ASC")
     @societies = Society.order("denominazione ASC")


    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dossier }
    end
  end

  # GET /dossiers/1/edit
  def edit
    @dossier = Dossier.find(params[:id])
    @names = Name.order("cognome_nome ASC")
     @unions = Union.order("denominazione ASC")
     @societies = Society.order("denominazione ASC")
  end

  # POST /dossiers
  # POST /dossiers.xml
  def create
    @dossier = Dossier.new(params[:dossier])

    respond_to do |format|
      if @dossier.save
        format.html { redirect_to(@dossier, :notice => 'Dossier was successfully created.') }
        format.xml  { render :xml => @dossier, :status => :created, :location => @dossier }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dossier.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dossiers/1
  # PUT /dossiers/1.xml
  def update
    @dossier = Dossier.find(params[:id])

    respond_to do |format|
      if @dossier.update_attributes(params[:dossier])
        format.html { redirect_to(@dossier, :notice => 'Dossier was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dossier.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dossiers/1
  # DELETE /dossiers/1.xml
  def destroy
    @dossier = Dossier.find(params[:id])
    @dossier.destroy

    respond_to do |format|
      format.html { redirect_to(dossiers_url) }
      format.xml  { head :ok }
    end
  end
end

private
  def sort_column
    Dossier.column_names.include?(params[:sort]) ? params[:sort] : "data"
  end
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

app/helpers/dossiers_helper.rb
module DossiersHelper
end

app/views/dossiers/_form.html.erb
<%= form_for(@dossier, :html => { :multipart => true }) do |f| %>
  <% if @dossier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dossier.errors.count, "error") %> prohibited this dossier from being saved:</h2>

      <ul>
      <% @dossier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<table>
<td>
  <div class="field">
<%= f.file_field :documento %>
  </div>

  <div class="field">
    <%= f.label :numero %><br />
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :oggetto %><br />
    <%= f.text_area :oggetto %>
  </div>
  <div class="field">
    <%= f.label :testo %><br />
    <%= f.text_area :testo %>
  </div>

 		Name:<br/>
		<div style="width:400px;height:400px;overflow-y: scroll; border:1px solid black;">
			<table border="3">
					<tr>
					<td>
				        <% @names.each do |name|  %>
				          <%= check_box_tag "dossier[name_ids][]", name.id, @dossier.names.include?(name) %>
				          <%= name.cognome_nome %>
						  <%= name.luogo_nascita %>
					      <%= name.data_nascita %> 
							<br/>	
				       <%end%>
				 </td>
				</tr>
			</table>
		</div>
</td>

<td>
		
		Associazione:<br/>
<div style="width:400px;height:400px;overflow-y: scroll; border:1px solid black;">
	<table border="3">
		<tr>
		<td>
	<% @unions.each do |union|%>
	<%= check_box_tag "dossier[union_ids][]", union.id, @dossier.unions.include?(union) %>
				          <%= union.denominazione %>
						
							<br/>	
				       <%end%>
				 </td>
				</tr>
			</table>
    </div>


Società:<br/>
<div style="width:400px;height:100px;overflow-y: scroll; border:1px solid black;">
	<table border="3">
		<tr>
		<td>
	<% @societies.each do |society|%>
	<%= check_box_tag "dossier[society_ids][]", society.id, @dossier.societies.include?(society) %>
				          <%= society.denominazione %>
						
							<br/>	
				       <%end%>
				 </td>
				</tr>
			</table>
		</div>

Associazione:<br/>
<div style="width:400px;height:400px;overflow-y: scroll; border:1px solid black;">
	<table border="3">
		<tr>
		<td>
	<% @unions.each do |union|%>
	<%= check_box_tag "dossier[union_ids][]", union.id, @dossier.unions.include?(union) %>
				          <%= union.denominazione %>
						
							<br/>	
				       <%end%>
				 </td>
				</tr>
			</table>
		</div>




  </td>
  </table>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dossiers/edit.html.erb
<h1>Editing dossier</h1>

<%= render 'form' %>

<%= link_to 'Show', @dossier %> |
<%= link_to 'Back', dossiers_path %>

app/views/dossiers/index.html.erb
<h1>Lista documenti</h1>

<table>
  <tr>
    <th><%= sortable "data" %></th>
    <th><%= sortable "numero" %></th>
    <th><%= sortable "oggetto" %></th>
    <th>Edit</th>

  </tr>

<% @dossiers.each do |dossier| %>
  <tr>
  	<td><%= dossier.data %></td>
    <td><%= dossier.numero %></td>  
    <td><%= dossier.oggetto %></td>

    <td><%= link_to 'Show', dossier %>
    <%= link_to 'Edit', edit_dossier_path(dossier) %>
    <%= link_to 'Destroy', dossier, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dossier', new_dossier_path %>

app/views/dossiers/new.html.erb
<h1>New dossier</h1>

<%= render 'form' %>

<%= link_to 'Back', dossiers_path %>

app/views/dossiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= link_to "Visualizza documento", @dossier.documento.url%>
</p>

<p>
  <b>Numero:</b>
  <%= @dossier.numero %>
</p>

<p>
  <b>Data:</b>
  <%= @dossier.data %>
</p>

<b>Elenco soggetti</b>
<ul>
    <% @names.each do |name| %>
      <li><%= link_to name.cognome_nome, :controller => :names, :action => :show, :id => name.id %></li>
    <% end %>
  </ul>
  
  <b>Associazioni</b>
	<ul>
	    <% @unions.each do |union| %>
	      <li><%= link_to union.denominazione, :controller => :unions, :action => :show, :id => union.id %></li>
	    <% end %>
	  </ul>

<p>
  <b>Oggetto:</b>
  <%= @dossier.oggetto %>
</p>

<p>
  <b>Testo:</b>
  <%= @dossier.testo %>
</p>


<%= link_to 'Edit', edit_dossier_path(@dossier) %> |
<%= link_to 'Back', dossiers_path %>