config/routes.rb
Dbros::Application.routes.draw do

 
  devise_for :admins

  resources :name_societies

  resources :societies

  resources :investigations

  resources :galleries

  resources :fascicles

  resources :dossiers

  resources :unions

  resources :associations

  resources :ambits

 	
  devise_for :users
  resources :users

 	
  resources :areas
 	resources :names
 	

	
	match '/names_search' => 'names#names_search'
	match '/show_search_results' => 'names#show_search_results'
	
	

	
	
	
	
	

  get "home/index"
  root :to => "home#index" 

end

app/models/union.rb
class Union < ActiveRecord::Base
belongs_to :area

has_and_belongs_to_many :dossiers
has_and_belongs_to_many :names
has_and_belongs_to_many :fascicles

def self.search(search)
  if search
    where('denominazione LIKE ?  or sede LIKE ?  or descrizione LIKE ? or areas.area_criminale LIKE ? or names.cognome_nome LIKE ?', "%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%").includes(:names, :area)
else
    scoped
  end
end
  
end

  

app/controllers/unions_controller.rb
class UnionsController < ApplicationController
  # GET /unions
  # GET /unions.xml
  before_filter :authenticate_user!, :except => [:show, :index]
  
  helper_method :sort_column, :sort_direction
  def index
    @unions = Union.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 3, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @unions }
    end
  end

  # GET /unions/1
  # GET /unions/1.xml
  def show
    @union = Union.find(params[:id])
    @area = @union.area
    @dossiers = @union.dossiers
    @names = @union.names
    @fascicles = @union.fascicles

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @union }
    end
  end

  # GET /unions/new
  # GET /unions/new.xml
  def new
    @union = Union.new
   @areas = Area.order("area_criminale ASC")
    @names = Name.order("cognome_nome ASC")
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @union }
    end
  end

  # GET /unions/1/edit
  def edit
    @union = Union.find(params[:id])
    @areas = Area.order("area_criminale ASC")
    @names = Name.order("cognome_nome ASC")
  end

  # POST /unions
  # POST /unions.xml
  def create
    @union = Union.new(params[:union])

    respond_to do |format|
      if @union.save
        format.html { redirect_to(@union, :notice => 'Union was successfully created.') }
        format.xml  { render :xml => @union, :status => :created, :location => @union }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @union.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /unions/1
  # PUT /unions/1.xml
  def update
    @union = Union.find(params[:id])

    respond_to do |format|
      if @union.update_attributes(params[:union])
        format.html { redirect_to(@union, :notice => 'Union was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @union.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /unions/1
  # DELETE /unions/1.xml
  def destroy
    @union = Union.find(params[:id])
    @union.destroy

    respond_to do |format|
      format.html { redirect_to(unions_url) }
      format.xml  { head :ok }
    end
  end
end

 private
  def sort_column  
  Union.column_names.include?(params[:sort]) ? params[:sort] : "denominazione"  
end
  def sort_direction  
  %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"  
end 

app/helpers/unions_helper.rb
module UnionsHelper
end

app/views/unions/_form.html.erb
<%= form_for(@union) do |f| %>
  <% if @union.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@union.errors.count, "error") %> prohibited this union from being saved:</h2>

      <ul>
      <% @union.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :denominazione %><br />
    <%= f.text_field :denominazione %>
  </div>
  <div class="field">
    <%= f.label :sede %><br />
    <%= f.text_field :sede %>
  </div>
  <div class="field">
    <%= f.label :descrizione %><br />
    <%= f.text_area :descrizione %>
  </div>
  
  <p>
	<%= f.label :names %><br />
	<%= f.collection_select :name_ids, @names, :id, :cognome_nome, {}, :multiple => true%>
 </p>
  
  
  <div class="field">
    <% if @areas.nil?
			puts "nil"
	else %>
	        <%= f.label :area_id %><br />
	        <%= f.collection_select :area_id, @areas, :id, :area_criminale, :include_blank=>true%>
	<%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unions/edit.html.erb
<h1>Editing union</h1>

<%= render 'form' %>

<%= link_to 'Show', @union %> |
<%= link_to 'Back', unions_path %>

app/views/unions/index.html.erb
<h1>Lista associazioni</h1>

<%= form_tag unions_path, :method => 'get' do %>  
  <p>  
    <%= text_field_tag :search, params[:search] %>  
    <%= submit_tag "Search", :name => nil %>  
  </p>  
<% end %>

<table>
  <tr>
  	<th><%= sortable "denominazione" %></th>
	<th><%= sortable "sede" %></th>
    <th><%= sortable "area_id", "Area" %></th>
    <th>Edit</th>
  </tr>

<% @unions.each do |union| %>
  <tr>
    <td><%= union.denominazione %></td>
    <td><%= union.sede %></td>
    <td><%= union.area.area_criminale %></td>
    <td><%= link_to 'Show', union %>
    <%= link_to 'Edit', edit_union_path(union) %>
    <%= link_to 'Destroy', union, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Union', new_union_path %>

<%= will_paginate @unions %>

app/views/unions/new.html.erb
<h1>New union</h1>

<%= render 'form' %>

<%= link_to 'Back', unions_path %>

app/views/unions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Denominazione:</b>
  <%= @union.denominazione %>
</p>

<p>
  <b>Sede:</b>
  <%= @union.sede %>
</p>

<p>
  <b>Descrizione:</b>
  <%= @union.descrizione %>
</p>

<p>
  <b>Area:</b>
  <%= @union.area.area_criminale %>
</p>

<b>Elenco soggetti</b>
<ul>
    <% @names.each do |name| %>
      <li><%= link_to name.cognome_nome, :controller => :names, :action => :show, :id => name.id %></li>
    <% end %>
  </ul>
  
  <p>
	<% if @fascicles.nil? %>
      Nil!
    <% else %>

	<% @fascicles.each do |fascicle| %>
    <b>Numero fascicolo:</b>
      <%= link_to fascicle.numero, :controller => :fascicles, :action => :show, :id => fascicle.id %><br/>
	<%end%>
	<%end%>
</p>

<table>
	<th>Documenti</th>
	<th>Numero</th>
	<th>Data</th>
	<th>Oggetto</th>
	<tr>
		<% @dossiers.each do |dossier|%>
		<td><%= link_to "Documento", dossier, :controller => :dossiers, :action => :show, :id => dossier.id%></td>
		<td><%= dossier.numero%></td>
		<td width=90px><%= dossier.data%></td>
		<td><%= dossier.oggetto%></td>
		</tr>
		<%end%>
	</table>


<%= link_to 'Edit', edit_union_path(@union) %> |
<%= link_to 'Back', unions_path %>