config/routes.rb
Dbros::Application.routes.draw do

 
  devise_for :admins

  resources :name_societies

  resources :societies

  resources :investigations

  resources :galleries

  resources :fascicles

  resources :dossiers

  resources :unions

  resources :associations

  resources :ambits

 	
  devise_for :users
  resources :users

 	
  resources :areas
 	resources :names
 	

	
	match '/names_search' => 'names#names_search'
	match '/show_search_results' => 'names#show_search_results'
	
	

	
	
	
	
	

  get "home/index"
  root :to => "home#index" 

end

app/models/name.rb
class Name < ActiveRecord::Base

belongs_to :area
belongs_to :ambit
belongs_to :association

has_and_belongs_to_many :dossiers
has_and_belongs_to_many :unions
has_and_belongs_to_many :fascicles
has_and_belongs_to_many :galleries
has_and_belongs_to_many :investigations


  has_many :name_societies, :dependent => :destroy
  has_many :societies, :through => :name_societies


  validates_uniqueness_of :cognome_nome, :case_sensitive => false, :message => ":  nome gia' presente!"
  validates_presence_of :cognome_nome, :message => ":  campo vuoto!"

  has_attached_file :photo, :styles => { :medium => "600x600>",
										:small => "300x300>",	:thumb => "100x100>" },
                    :url  => "/assets/avatar/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/avatar/:id/:style/:basename.:extension"


def self.search(search)
  if search
    where('cognome_nome LIKE ? or luogo_nascita LIKE ? or data_nascita LIKE ? or residenza LIKE ? or cittadinanza LIKE ?
          or ambits.ambito_criminale LIKE ? or areas.area_criminale LIKE ? or associations.associazione_criminale LIKE ?
          or unions.denominazione LIKE ?',
          "%#{search}%","%#{search}%", "%#{search}%", "%#{search}%","%#{search}%","%#{search}%","%#{search}%", "%#{search}%",
          "%#{search}%").includes(:ambit, :area, :association, :unions )
  else
    scoped
  end
end


end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  # GET /names
  # GET /names.xml
  before_filter :authenticate_user!, :only => [:edit, :new]
  before_filter :authenticate_admin!, :only => [ :destroy]

  helper_method :sort_column, :sort_direction

  respond_to :html, :xml

  def index

    #@names = Name.order("cognome_nome desc").limit(3) 
    @names = Name.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 3, :page => params[:page])
    #@names = Name.where("luogo_nascita LIKE '%mi%'").paginate(:per_page => 3, :page => params[:page])

    respond_with @names
  end



  # GET /names/1
  # GET /names/1.xml
  def show
    @name = Name.find(params[:id])
    @area = @name.area
    @ambit = @name.ambit
    @association = @name.association
    @dossiers = @name.dossiers
    @fascicles = @name.fascicles
    @galleries = @name.galleries
    @investigations = @name.investigations
    @unions = @name.unions
    @societies = @name.societies


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @name }
      format.pdf { render :layout => false }
    end
  end

  # GET /names/new
  # GET /names/new.xml
  def new
    @name = Name.new
    @areas = Area.order("area_criminale ASC")
    @ambits = Ambit.order("ambito_criminale ASC")
    @associations = Association.order("associazione_criminale ASC")
    @dossiers = Dossier.all
    @unions = Union.order("denominazione ASC")
    @investigations = Investigation.order("indagine ASC")

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @name }
    end
  end

  # GET /names/1/edit
  def edit
    @name = Name.find(params[:id])
    @areas = Area.order("area_criminale ASC")
    @ambits = Ambit.order("ambito_criminale ASC")
    @associations = Association.order("associazione_criminale ASC")
    @dossiers = Dossier.all
    @unions = Union.order("denominazione ASC")
    @investigations = Investigation.order("indagine ASC")
  end

  # POST /names
  # POST /names.xml
  def create
    @name = Name.new(params[:name])


    respond_to do |format|
      if @name.save

        format.html { redirect_to(@name, :notice => 'Name was successfully created.') }
        format.xml  { render :xml => @name, :status => :created, :location => @name }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @name.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /names/1
  # PUT /names/1.xml
  def update
    @name = Name.find(params[:id])

    respond_to do |format|
      if @name.update_attributes(params[:name])
        format.html { redirect_to(@name, :notice => 'Name was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @name.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.xml
  def destroy
    @name = Name.find(params[:id])
    @name.destroy

    respond_to do |format|
      format.html { redirect_to(names_url) }
      format.xml  { head :ok }
    end
  end

  def names_search

  end

  def show_search_results
    search_fields = params[:search_fields]

    condizioni = []
    valori = {}
    unless search_fields.nil?
      search_fields.each do |campo, valore|
        next if valore.blank?
        condizioni << "#{campo} like :#{campo}"
        valori[campo.intern] = "%#{valore}%"
      end
    end

    unless params[:data_field].blank?
      data = params[:data_field][:data_nascita]
      logger.debug "data = #{data}"
    end

    #logger.debug "condizioni #{condizioni}"

 #@names = Name.joins(:ambit).where(condizioni.join(" AND "), valori)

 #
  @names = Name.joins("LEFT JOIN ambits ON names.ambit_id=ambits.id 
                      LEFT JOIN areas ON names.area_id=areas.id 
                      LEFT JOIN associations ON names.association_id=associations.id").where(condizioni.join(" AND "), valori)


  end

  private
  def sort_column
    Name.column_names.include?(params[:sort]) ? params[:sort] : "cognome_nome"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/names/_form.html.erb
<%= form_for(@name, :html => { :multipart => true }) do |f| %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<table>
<td>
  <div class="field">
    <%= f.label :cognome_nome %><br />
    <%= f.text_field :cognome_nome %>
  </div>
  <div class="field">
    <%= f.label :luogo_nascita %><br />
    <%= f.text_field :luogo_nascita %>
  </div>
  <div class="field">
    <%= f.label :data_nascita %><br />
    <%= f.date_select :data_nascita, :include_blank => true, :start_year => Time.now.year , :end_year=> Time.now.year - 80, :use_month_numbers => true  %>
  </div>
  <div class="field">
    <%= f.label :cod_fiscale %><br />
    <%= f.text_field :cod_fiscale %>
  </div>
  <div class="field">
    <%= f.label :residenza %><br />
    <%= f.text_field :residenza %>
  </div>
  <div class="field">
    <%= f.label :via %><br />
    <%= f.text_field :via %>
  </div>
  <div class="field">
    <%= f.label :domicilio %><br />
    <%= f.text_field :domicilio %>
  </div>
  <div class="field">
    <%= f.label :cittadinanza %><br />
    <%= f.text_field :cittadinanza %>
  </div>
  <div class="field">
    <%= f.label :professione %><br />
    <%= f.text_field :professione %>
  </div>
  <div class="field">
    <%= f.label :soprannome %><br />
    <%= f.text_field :soprannome %>
  </div>
  <div class="field">
    <%= f.label :alias %><br />
    <%= f.text_field :alias %>
  </div>
  <div class="field">
    <%= f.label :note_generali %><br />
    <%= f.text_field :note_generali %>
  </div>
  
  <div class="field">
     <% if @associations.nil?
			puts ""
	else %>
	        <%= f.label :associations_id %><br />
	        <%= f.collection_select :association_id, @associations, :id, :associazione_criminale, :include_blank=>true%>
	<%end%>
  </div>
  
  <div class="field">
    <% if @ambits.nil?
			puts ""
	else %>
	        <%= f.label :ambit_id %><br />
	        <%= f.collection_select :ambit_id, @ambits, :id, :ambito_criminale, :include_blank=>true%>
	<%end%>
	
  </div>
  
  <div class="field">
    <% if @areas.nil?
			puts ""
	else %>
	        <%= f.label :area_id %><br />
	        <%= f.collection_select :area_id, @areas, :id, :area_criminale, :include_blank=>true%>
	<%end%>
  </div>
</td>
   
<td>
  <div class="field">
    Fotografia:<br/>
        <%= f.file_field :photo %>
  </div>
 

	<% if @unions.nil?
		puts "nil"
	else %>
	        <%= f.label "Associazione" %><br />
	        <%= f.collection_select :union_ids, @unions, :id, :denominazione, :include_blank=>true%>
	<%end%>

</td>

 <td>
<% if @investigations.nil?
		puts "nil"
	else %>
	Indagini:<br/>
        <% @investigations.each do |investigation|  %>
          <%= check_box_tag "name[investigation_ids][]", investigation.id, @name.investigations.include?(investigation) %>
          <%= investigation.indagine %>
			- Reparto: <b><%=investigation.reparto%></b><br/>
        <%end%>
<%end%>
      </td>


</table>
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/names/_names.html.erb
<p align="right"><%= link_to 'New Name', new_name_path %></p>

<%= hidden_field_tag :direction, params[:direction] %>  
<%= hidden_field_tag :sort, params[:sort] %> 

<table>
  <tr>
    <th><%= sortable "cognome_nome" %></th>
    <th><%= sortable "luogo_nascita" %></th> 
    <th><%= sortable "data_nascita" %></th> 
    <th><%= sortable "residenza" %></th> 
    <th><%= sortable "cittadinanza" %></th>
    <th><%= sortable "association_id", "Associazione crim." %></th>
    <th><%= sortable "ambit_id", "Ambito crim." %></th>
    <th><%= sortable "area_id", "Area" %></th>
    <th> Foto </th>
    <th>Edit</th>
  
  </tr>

<% @names.each do |name| %>
  <tr>
    <td><%= link_to name.cognome_nome, name %></td>
    <td><%= name.luogo_nascita %></td>
    <td><%= name.data_nascita %></td>
    <td><%= name.residenza %></td>
    <td><%= name.cittadinanza %></td>
    
    
	<td>
	<% if name.association.nil? %>
  	<% else %>
		<%=name.association.associazione_criminale %>
    </td>
	<%end%>
	
    <td>
	<% if name.ambit.nil? %>
  	<% else %>
		<%=name.ambit.ambito_criminale %>
    </td>
	<%end%>
    
    <td>
	<% if name.area.nil? %>
  	<% else %>
		<%=name.area.area_criminale %>
    </td>
	<%end%>
    <td><%= image_tag name.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', name %>
    <%= link_to 'Edit', edit_name_path(name) %>
    <%= link_to 'Destroy', name, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
    
    
    <%= will_paginate @names %>

app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render 'form' %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

app/views/names/index.html.erb
<h1>Lista soggetti</h1>
    
      
    <%= form_tag names_path, :method => 'get', :id => "names_search" do %>  
      <p>  
        <%= text_field_tag :search, params[:search] %>  
        <%= submit_tag "Search", :name => nil %>  
      </p>  
     <div id="names"><%= render 'names' %></div>  
    <% end %>  

app/views/names/index.js.erb
$('#names').html('<%= escape_javascript(render("names")) %>');

app/views/names/names_search.html.erb
<%= form_tag 'show_search_results', :method => 'get' do %>


<h2>Search Anagrafica</h2>  
<table>
    <tr>
      <td>
        <label>Cognome e nome:<br/>
          <%= text_field :search_fields, "cognome_nome", :id => "cognome_nome"%>
        </label>
      </td>
      <td>
        <label>Luogo nascita:<br/>
          <%= text_field :search_fields, "luogo_nascita",:id => "luogo_nascita" %>
        </label>
      </td>
  </tr>
  <tr>
      <td>
        <label>Data nascita:<br/>
          <%= text_field :search_fields, "data_nascita",:id => "data_nascita" %>
        </label>
      </td>
      <td>
        <label>Residenza:<br/>
          <%= text_field :search_fields, "residenza",:id => "residenza" %>
        </label>
      </td>
  </tr>
  <tr>
      <td>
        <label>Via:<br/>
          <%= text_field :search_fields, "via",:id => "via" %>
        </label>
      </td>
      <td>
        <label>Domicilio:<br/>
          <%= text_field :search_fields, "domicilio",:id => "domicilio" %>
        </label>
      </td>
    </tr>
    <tr>
      <td>
        <label>CF:<br/>
          <%= text_field :search_fields, "cod_fiscale",:id => "cod_fiscale" %>
        </label>
      </td>
      <td>
        <label>Cittadinanza:<br/>
          <%= text_field :search_fields, "cittadinanza",:id => "cittadinanza" %>
        </label>
      </td>
  </tr>
  <tr>
      <td>
        <label>Professione:<br/>
          <%= text_field :search_fields, "professione",:id => "professione" %>
        </label>
      </td>
      <td>
        <label>Alias:<br/>
          <%= text_field :search_fields, "alias",:id => "alias" %>
        </label>
      </td>
  </tr>
  <tr>
      <td>
        <label>Soprannome:<br/>
          <%= text_field :search_fields, "soprannome",:id => "soprannome" %>
        </label>
      </td>
	<td>
	    <label>Ambito:<br/>
	      	 <%= text_field :search_fields, "ambito_criminale", :id => "ambito_criminale" %>
	        </label>
	  </td>
  </tr>
  <tr>
  <td>
    <label>Area:<br/>
      	 <%= text_field :search_fields, "area_criminale", :id => "area_criminale" %>
        </label>
  </td>
	<td>
	    <label>Associazione crim.:<br/>
	      	 <%= text_field :search_fields, "associazione_criminale", :id => "associazione_criminale" %>
	        </label>
	  </td>
  <tr>
  </tr>


  <tr>
      <td>
        <label>Note generali:<br/>
          <%= text_area :search_fields, "note_generali",:id => "note_generali" %>
        </label>
      </td>

      <td>
        <label>note associazione:<br/>
          <%= text_area :search_fields, "note_associazione",:id => "note_associazione" %>
        </label>
      </td>
    </tr>

  </table>

  <%= submit_tag "Search" %>
<% end %>

app/views/names/new.html.erb
<h1>New name</h1>

<%= render 'form' %>

<%= link_to 'Back', names_path %>

app/views/names/search.html.erb
<% form_tag "show_search_results", :method => 'get' do %>


<h2>Search Anagrafica</h2>  
<table>
    <tr>
      <td>
        <label>Cognome e nome:<br/>
          <%= text_field :search_fields, "cognome_nome", :id => "cognome_nome" %>
        </label>
      </td>
      <td>
        <label>Luogo nascita:<br/>
          <%= text_field :search_fields, "luogo_nascita",:id => "luogo_nascita" %>
        </label>
      </td>
  </tr>
  <tr>
      <td>
        <label>Data nascita:<br/>
          <%= text_field :search_fields, "data_nascita",:id => "data_nascita" %>
        </label>
      </td>
      <td>
        <label>Residenza:<br/>
          <%= text_field :search_fields, "residenza",:id => "residenza" %>
        </label>
      </td>
  </tr>
  <tr>
      <td>
        <label>Via:<br/>
          <%= text_field :search_fields, "via",:id => "via" %>
        </label>
      </td>
      <td>
        <label>Domicilio:<br/>
          <%= text_field :search_fields, "domicilio",:id => "domicilio" %>
        </label>
      </td>
    </tr>
    <tr>
      <td>
        <label>CF:<br/>
          <%= text_field :search_fields, "cod_fiscale",:id => "cod_fiscale" %>
        </label>
      </td>
      <td>
        <label>Cittadinanza:<br/>
          <%= text_field :search_fields, "cittadinanza",:id => "cittadinanza" %>
        </label>
      </td>
  </tr>
  <tr>
      <td>
        <label>Professione:<br/>
          <%= text_field :search_fields, "professione",:id => "professione" %>
        </label>
      </td>
      <td>
        <label>Alias:<br/>
          <%= text_field :search_fields, "alias",:id => "alias" %>
        </label>
      </td>
  </tr>
  <tr>
      <td>
        <label>Soprannome:<br/>
          <%= text_field :search_fields, "soprannome",:id => "soprannome" %>
        </label>
      </td>
	<td>
	    <label>Ambito:<br/>
	      	 <%= text_field :search_fields, "ambito_criminale", :id => "ambito_criminale" %>
	        </label>
	  </td>
  </tr>
  <td>
    <label>Area:<br/>
      	 <%= text_field :search_fields, "area_criminale", :id => "area_criminale" %>
        </label>
  </td>
	<td>
	    <label>Associazione:<br/>
	      	 <%= text_field :search_fields, "associazione_criminale", :id => "associazione_criminale" %>
	        </label>
	  </td>
  <tr>
  </tr>
  <tr>
      <td>
        <label>Note generali:<br/>
          <%= text_area :search_fields, "note_generali",:id => "note_generali" %>
        </label>
      </td>

      <td>
        <label>note associazione:<br/>
          <%= text_area :search_fields, "note_associazione",:id => "note_associazione" %>
        </label>
      </td>
    </tr>

  </table>

  <%= submit_tag "Search" %>
<% end %>

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<table>
<th>Generalità</th>
<th> Foto</th>

<tr>
<td>
<p>
  <b>Cognome nome:</b>
  <%= @name.cognome_nome %>
</p>

<p>
  <b>Luogo nascita:</b>
  <%= @name.luogo_nascita %>
</p>

<p>
  <b>Data nascita:</b>
  <%= @name.data_nascita %>
</p>

<p>
  <b>Cod fiscale:</b>
  <%= @name.cod_fiscale %>
</p>

<p>
  <b>Residenza:</b>
  <%= @name.residenza %>
</p>

<p>
  <b>Via:</b>
  <%= @name.via %>
</p>

<p>
  <b>Domicilio:</b>
  <%= @name.domicilio %>
</p>

<p>
  <b>Cittadinanza:</b>
  <%= @name.cittadinanza %>
</p>

<p>
  <b>Professione:</b>
  <%= @name.professione %>
</p>

<p>
  <b>Soprannome:</b>
  <%= @name.soprannome %>
</p>

<p>
  <b>Alias:</b>
  <%= @name.alias %>
</p>


<p>
  <b>Association:</b>
   <% if @association.nil? %>
          
        <% else %>
         <%=h @association.associazione_criminale %>
        <%end%>
</p>

<p>
  <b>Ambito criminale :</b>
        <% if @ambit.nil? %>
          
        <% else %>
          <%=h @ambit.ambito_criminale %>       
        <%end%>
</p>

   <b>Area :</b>
        <% if @area.nil? %>
          
        <% else %>
         <%=h @area.area_criminale %>
        <%end%>
      </p>
      
      <p>
      
      <p>
	<% if @fascicles.nil? %>
      Nil!
    <% else %>

	<% @fascicles.each do |fascicle| %>
    <b>Numero fascicolo:</b>
      <%= link_to fascicle.numero, :controller => :fascicles, :action => :show, :id => fascicle.id %><br/>
	<%end%>
	<%end%>
</p>
      
      
      
      
  <b>Note generali:</b>
  <%= @name.note_generali %>
</p>
</td>

<td>      
<p align=center>
    <%=link_to (image_tag @name.photo.url :small),  (@name.photo.url :original) %>
</p>

<p align="center"> 	<%=link_to "Scheda personale PDF", name_path(@name, :pdf)%> </p>

</td>
</tr>
</table>

<table>

	<th>Documenti</th>
	<th>Numero</th>
	<th>Data</th>
	<th>Oggetto</th>
	<tr>
		<% @dossiers.each do |dossier|%>
		<td><%= link_to "Documento", dossier, :controller => :dossiers, :action => :show, :id => dossier.id%></td>
		<td><%= dossier.numero%></td>
		<td width=90px><%= dossier.data%></td>
		<td><%= dossier.oggetto%></td>
		</tr>
   <%end%>
</table>

<table>
	<th>Gallery</th>
	<tr>
	<td>
		<% @galleries.each do |gallery|%>
      <%= link_to (image_tag gallery.photo.url :thumb), :controller => :galleries, :action => :show, :id => gallery.id%>
		<%end%>	
	</td>
	</tr>
</table>

<table>
	<th>Associazione</th>
	<th>Sede</th>
	<th>area</th>
	
	<tr>	
	<% @unions.each do |union| %>
		<td><%= link_to union.denominazione, union, :controller => :unions, :action => :show, :id => union.id %></td>
		<td><%= union.sede%></td>
	<% if union.area.nil? %>
		     <td> Non definita </td>
	<% else %>
		<td><%= union.area.area_criminale%></td>
	<%end%>		
		</tr>
	<%end%>
</table>


<table>
	<th>Indagini</th>
	<tr>
	<td>
      <ul>
        <% @investigations.each do |investigation| %>
        <li><%= link_to investigation.indagine, :controller => :investigations, :action => :show, :id => investigation.id %>
		- Reparto: 
		<b><%=investigation.reparto%></b>
	
	</li>
        <% end %>
      </ul>
	</td>
	</tr>
</table>


<table>
	<th>Società</th>
	<th>Forma giuridica</th>
	<th>Sede</th>
	<tr>
	    <% @name.name_societies.each do |join| %>
	      	<td><%= link_to join.society.denominazione, :controller => :societies, :action => :show, :id => join.society.id %></td>
			<td><%=join.society.forma_giuridica%></td>
			<td><%=join.society.sede%></td>
			</tr>
		<%end%>
</table>



<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>

app/views/names/show_search_results.html.erb
<h1>Lista soggetti</h1>
    
      
   <p align="right"><%= link_to 'New Name', new_name_path %></p>

<table>
  <tr>
    <th>Cognome nome </th>
    <th>Luogo nascita</th> 
    <th>Data nascita</th> 
    <th>Residenza" </th> 
    <th>Cittadinanza</th>
    <th>Associazione crim.</th>
    <th>Ambito crim.</th>
    <th>Area</th>
    <th>Foto </th>
    <th>Edit</th>
  
  </tr>

<% @names.each do |name| %>
  <tr>
    <td><%= link_to name.cognome_nome, name %></td>
    <td><%= name.luogo_nascita %></td>
    <td><%= name.data_nascita %></td>
    <td><%= name.residenza %></td>
    <td><%= name.cittadinanza %></td>
    
    
	<td>
	<% if name.association.nil? %>
  	<% else %>
		<%=name.association.associazione_criminale %>
    </td>
	<%end%>
	
    <td>
	<% if name.ambit.nil? %>
  	<% else %>
		<%=name.ambit.ambito_criminale %>
    </td>
	<%end%>
    
    <td>
	<% if name.area.nil? %>
  	<% else %>
		<%=name.area.area_criminale %>
    </td>
	<%end%>
    <td><%= image_tag name.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', name %>
    <%= link_to 'Edit', edit_name_path(name) %>
    <%= link_to 'Destroy', name, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
    
    